name: Nationwide Weather Monitoring

on:
  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  weather-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Create environment file
        run: |
          echo "NWS_API_URL=${{ secrets.NWS_API_URL }}" >> .env
          echo "MONITOR_SCOPE=${{ secrets.MONITOR_SCOPE }}" >> .env
          echo "MIN_ALERT_SEVERITY=${{ secrets.MIN_ALERT_SEVERITY }}" >> .env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_TO=${{ secrets.EMAIL_TO }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "GENERATE_MAPS=true" >> .env
          echo "CHECK_INTERVAL=15" >> .env


      - name: Run weather monitor
        run: |
          python main.py
